networks:
  saas:
    driver: bridge

volumes:
  db_mysql:

services:
  laravel:
    build:
      context: 'docker'
      dockerfile: 'Dockerfile'
      args:
        WWWUSER: 'laravel'
        UID: '1000'
        NODE_VERSION: '20'
    container_name: saas-laravel
    image: project-base
    ports:
      - '5173:5173'
    volumes:
      - './:/var/www/html'
    networks:
      - saas

  nginx:
    image: nginx:1.26.2
    container_name: saas-nginx
    working_dir: /var/www/html/public
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./public:/var/www/html/public
    networks:
      - saas
    
  mysql:
    image: mysql:8.0
    container_name: saas-mysql
    volumes: 
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 3
      timeout: 5s
    networks: 
      - saas